# Generated by Django 5.2.6 on 2025-09-24 17:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_type', models.CharField(choices=[('rent', 'Monthly Rent'), ('deposit', 'Security Deposit'), ('service', 'Service Charge'), ('late_fee', 'Late Fee'), ('maintenance', 'Maintenance Fee'), ('other', 'Other')], default='rent', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('check', 'Check'), ('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, help_text='When the payment was actually completed', null=True)),
                ('payment_month', models.PositiveIntegerField(blank=True, help_text='Month this payment covers (1-12)', null=True)),
                ('payment_year', models.PositiveIntegerField(blank=True, help_text='Year this payment covers', null=True)),
                ('reference', models.CharField(blank=True, help_text='Receipt number, transaction ID, etc.', max_length=100, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Payment gateway transaction ID (Stripe, M-Pesa, etc.)', max_length=200, null=True)),
                ('payment_gateway', models.CharField(blank=True, help_text='Which system processed this payment', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['landlord', 'caretaker']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.unit')),
            ],
            options={
                'ordering': ['-date_paid', '-date_created'],
                'indexes': [models.Index(fields=['tenant', '-date_paid'], name='payments_pa_tenant__855994_idx'), models.Index(fields=['unit', '-date_paid'], name='payments_pa_unit_id_b0fcdf_idx'), models.Index(fields=['payment_year', 'payment_month'], name='payments_pa_payment_5a99ce_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('expected_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
            options={
                'ordering': ['-year', '-month', 'unit'],
                'unique_together': {('unit', 'year', 'month')},
            },
        ),
    ]
