# Generated by Django 5.2.6 on 2025-09-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the property(e.g Villa Rosa Gardens)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional text about the property', null=True)),
                ('total_units', models.PositiveIntegerField(default=0, help_text='Total number of units in this property')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretakers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'caretaker'}, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Unit identifier (e.g C20, Unit 5)', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional unit description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_unit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['property', 'unit_number'],
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
